import {
  fontSize,
  fontFamily,
  fill,
  opacity,
  stroke,
  strokeWidth,
} from 'config/moduleConfig';

export const modulesData = [
  {
    fontSize,
    fontFamily,
    fill,
    opacity,
    strokeWidth,
    stroke: "black", 
    width: 30,
    height: 30,
    rotation: 0,
    boundToSideIndex: null,
    innerGroupX: 0,
    innerGroupY: 0,
    text: "LED",
    textX: 6,
    textY: 11,
    imageX: 3.75,
    imageY: 8,
    imageWidth: 22.5,
    imageHeight: 14,
    imageSrc: 'images/LED.svg',
    imageNode: null,
    iconSrc: 'images/LED-icon.svg',
    iconHeight: "70px",
    price: "$9.75",
    info: null
  },
  {
    fontSize,
    fontFamily,
    fill,
    opacity,
    strokeWidth,
    stroke: "black", 
    width: 65,
    height: 100,
    rotation: 0,
    boundToSideIndex: null,
    innerGroupX: 0,
    innerGroupY: 0,
    text: "5V/5A Regulator",
    textX: 15,
    textY: 13,
    imageX: 12.5,
    imageY: 10,
    imageWidth: 40,
    imageHeight: 80,
    imageSrc: 'images/regulator-5V5A.svg',
    imageNode: null,
    iconSrc: 'images/regulator-5V5A-icon.svg',
    iconHeight: "70px",
    price: "$9.75",
    info: null
  },
  {
    fontSize,
    fontFamily,
    fill,
    opacity,
    stroke,
    strokeWidth,
    width: 90,
    height: 110,
    rotation: 0,
    boundToSideIndex: 0,
    innerGroupX: 0,
    innerGroupY: 0,
    text: "Barrel Connector (20V 3A)",
    textX: 10,
    textY: 25,
    imageX: 10,
    imageY: 10,
    imageWidth: 70,
    imageHeight: 100,
    imageSrc: 'images/barrel-connector.svg',
    imageNode: null,
    iconSrc: 'images/barrel-connector-icon.svg',
    iconHeight: "70px",
    price: null,
    info: null
  },
  {
    fontSize,
    fontFamily,
    fill,
    opacity,
    stroke,
    strokeWidth,
    width: 75,
    height: 75,
    rotation: 0,
    boundToSideIndex: null,
    text: "3.5V/1.5A Regulator",
    textX: 15,
    textY: 20,
    innerGroupX: null,
    innerGroupY: null,
    imageX: null,
    imageY: null,
    imageWidth: null,
    imageHeight: null,
    imageSrc: null,
    iconSrc: 'images/regulator-icon.svg',
    iconHeight: "70px",
    price: null,
    info: null
  }
]