export const  ENTITY_UPDATE = 'ENTITY_UPDATE';
export const  ENTITY_DELETE = 'ENTITY_DELETE';
export const  ENTITY_CREATE = 'ENTITY_CREATE';
export const  ENTITY_CREATE_REQUEST= 'ENTITY_CREATE_REQUEST';
export const  ENTITY_CREATE_SUCCESS = 'ENTITY_CREATE_SUCCESS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
