export const demoProject = {
  "_id": "5911da0c1e57bb5cb71ca95a",
  "name": "Dual Ethernet Board",
  "__v": 0,
  "moduleBank": [],
  "modules": [
    {
      "price": 12,
      "iconHeight": "70px",
      "iconSrc": "images/usb-ethernet-module-icon.svg",
      "imageSrc": "images/usb-ethernet-module.svg",
      "imageHeight": 145,
      "imageWidth": 105,
      "imageY": 90,
      "imageX": 35,
      "textY": 32.5,
      "textX": 40,
      "text": "USB Ethernet Module",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 225,
      "width": 175,
      "stroke": "#ffff64",
      "y": 91,
      "x": 604.5,
      "_id": "5911e0cd1e57bb5cb71ca96a"
    },
    {
      "price": 12,
      "iconHeight": "70px",
      "iconSrc": "images/usb-ethernet-module-icon.svg",
      "imageSrc": "images/usb-ethernet-module.svg",
      "imageHeight": 145,
      "imageWidth": 105,
      "imageY": 90,
      "imageX": 35,
      "textY": 32.5,
      "textX": 40,
      "text": "USB Ethernet Module",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 225,
      "width": 175,
      "stroke": "#ffff64",
      "y": 93,
      "x": 425.5,
      "_id": "5911e0cd1e57bb5cb71ca969"
    },
    {
      "price": 5,
      "iconHeight": "70px",
      "iconSrc": "images/microsd-slot-icon.svg",
      "imageSrc": "images/microsd-slot.svg",
      "imageHeight": 75,
      "imageWidth": 86,
      "imageY": 4.5,
      "imageX": 3.5,
      "textY": 20,
      "textX": 10,
      "text": "microSD slot",
      "innerGroupY": 88.5,
      "innerGroupX": 6.5,
      "boundToSideIndex": 3,
      "rotation": 270,
      "height": 82,
      "width": 95,
      "stroke": "#d4b9ff",
      "y": 172,
      "x": 778.5,
      "_id": "5911e0cd1e57bb5cb71ca968"
    },
    {
      "price": 2.25,
      "iconHeight": "70px",
      "iconSrc": "images/USB-hub-4-port-icon.svg",
      "imageSrc": "images/USB-hub-4-port.svg",
      "imageHeight": 30,
      "imageWidth": 30,
      "imageY": 10,
      "imageX": 20,
      "textY": 12.5,
      "textX": 5,
      "text": "USB Hub 4 Port",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 60,
      "width": 60,
      "stroke": "#909bef",
      "y": 12,
      "x": 74,
      "_id": "5911e0cd1e57bb5cb71ca967"
    },
    {
      "price": 2.25,
      "iconHeight": "70px",
      "iconSrc": "images/micro-b-jack-icon.svg",
      "imageSrc": "images/micro-b-jack.svg",
      "imageHeight": 31,
      "imageWidth": 46,
      "imageY": 14,
      "imageX": 7.5,
      "textY": 5,
      "textX": 7.5,
      "text": "Micro-B Jack",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 40,
      "width": 60,
      "stroke": "#e5b758",
      "y": 277,
      "x": 318,
      "_id": "5911e0cd1e57bb5cb71ca966"
    },
    {
      "price": 15,
      "iconHeight": "70px",
      "iconSrc": "images/COM-connector.svg",
      "imageSrc": "images/COM-connector.svg",
      "imageHeight": 125,
      "imageWidth": 250,
      "imageY": 4,
      "imageX": 2,
      "textY": 32,
      "textX": 76,
      "text": "COM Connector",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 133,
      "width": 254,
      "stroke": "#90f5ff",
      "y": 1.5,
      "x": 165,
      "_id": "5911e0cd1e57bb5cb71ca965"
    },
    {
      "price": 13.5,
      "iconHeight": "70px",
      "iconSrc": "images/dual-stacked-usb-icon.svg",
      "imageSrc": "images/dual-stacked-usb.svg",
      "imageHeight": 135,
      "imageWidth": 100,
      "imageY": 35,
      "imageX": 10,
      "textY": 55,
      "textX": 19,
      "text": "Dual Stacked USB",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 170,
      "width": 120,
      "stroke": "#66ccff",
      "y": 186,
      "x": 101,
      "_id": "5911e0cd1e57bb5cb71ca964"
    },
    {
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-5V5A-icon.svg",
      "imageSrc": "images/regulator-5V5A.svg",
      "imageHeight": 80,
      "imageWidth": 40,
      "imageY": 10,
      "imageX": 12.5,
      "textY": 25,
      "textX": 15,
      "text": "5V/5A Regulator",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 100,
      "width": 65,
      "stroke": "#8bff8f",
      "y": 12,
      "x": 794.5,
      "_id": "5911e0cd1e57bb5cb71ca963"
    },
    {
      "price": 1.2,
      "iconHeight": "70px",
      "iconSrc": "images/tactile-switch-icon.svg",
      "imageSrc": "images/tactile-switch.svg",
      "imageHeight": 25,
      "imageWidth": 25,
      "imageY": 5,
      "imageX": 5,
      "textY": 8,
      "textX": 4,
      "text": "Tactile Switch",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 35,
      "width": 35,
      "stroke": "#e5b758",
      "y": 279.5,
      "x": 382.5,
      "_id": "5911e0cd1e57bb5cb71ca962"
    },
    {
      "price": 4.25,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-icon.svg",
      "imageSrc": null,
      "imageHeight": null,
      "imageWidth": null,
      "imageY": null,
      "imageX": null,
      "innerGroupY": null,
      "innerGroupX": null,
      "textY": 20,
      "textX": 15,
      "text": "3.5V/1.5A Regulator",
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 75,
      "width": 75,
      "stroke": "#ca73ff",
      "y": 5.5,
      "x": 611.5,
      "_id": "5911e0cd1e57bb5cb71ca961"
    },
    {
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#ff00ff",
      "y": 284,
      "x": 822,
      "_id": "5911e0cd1e57bb5cb71ca960"
    },
    {
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#ff00ff",
      "y": 284,
      "x": 785,
      "_id": "5911e0cd1e57bb5cb71ca95f"
    },
    {
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#ff00ff",
      "y": 285,
      "x": 23,
      "_id": "5911e0cd1e57bb5cb71ca95e"
    },
    {
      "price": 5,
      "iconHeight": "70px",
      "iconSrc": "images/barrel-connector-icon.svg",
      "imageSrc": "images/barrel-connector.svg",
      "imageHeight": 100,
      "imageWidth": 70,
      "imageY": 10,
      "imageX": 10,
      "textY": 25,
      "textX": 10,
      "text": "Barrel Connector (20V 3A)",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 110,
      "width": 90,
      "stroke": "#debd37",
      "y": 219,
      "x": 223,
      "_id": "5911e0cd1e57bb5cb71ca95d"
    },
    {
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-5V5A-icon.svg",
      "imageSrc": "images/regulator-5V5A.svg",
      "imageHeight": 80,
      "imageWidth": 40,
      "imageY": 10,
      "imageX": 12.5,
      "textY": 25,
      "textX": 15,
      "text": "5V/5A Regulator",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 100,
      "width": 65,
      "stroke": "#8bff8f",
      "y": 97,
      "x": 21.5,
      "_id": "5911e0cd1e57bb5cb71ca95c"
    },
    {
      "price": 1.2,
      "iconHeight": "70px",
      "iconSrc": "images/tactile-switch-icon.svg",
      "imageSrc": "images/tactile-switch.svg",
      "imageHeight": 25,
      "imageWidth": 25,
      "imageY": 5,
      "imageX": 5,
      "textY": 8,
      "textX": 4,
      "text": "Tactile Switch",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 35,
      "width": 35,
      "stroke": "#e5b758",
      "y": 278.5,
      "x": 60.5,
      "_id": "5911e0cd1e57bb5cb71ca95b"
    }
  ],
  "boardSpecs": {
    "y": 97,
    "x": 348,
    "thumbnail": "{\"attrs\":{\"width\":884,\"height\":335},\"className\":\"Stage\",\"children\":[{\"attrs\":{\"name\":\"boardLayer\"},\"className\":\"Layer\",\"children\":[{\"attrs\":{\"name\":\"boardGroup\",\"x\":10,\"y\":10,\"width\":864,\"height\":315,\"draggable\":\"true\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"name\":\"board\",\"x\":107,\"width\":864,\"height\":315,\"fill\":\"#e3e3e5\",\"opacity\":\"0.5\",\"stroke\":\"#ccc\",\"isStrokeRed\":false},\"className\":\"Rect\"},{\"attrs\":{\"x\":107,\"stroke\":\"#666\",\"fill\":\"#ddd\",\"radius\":\"8\",\"name\":\"topLeft\",\"draggable\":\"true\",\"dragOnTop\":\"false\"},\"className\":\"Circle\"},{\"attrs\":{\"x\":971,\"stroke\":\"#666\",\"fill\":\"#ddd\",\"radius\":\"8\",\"name\":\"topRight\",\"draggable\":\"true\",\"dragOnTop\":\"false\"},\"className\":\"Circle\"},{\"attrs\":{\"x\":107,\"y\":315,\"stroke\":\"#666\",\"fill\":\"#ddd\",\"radius\":\"8\",\"name\":\"bottomLeft\",\"draggable\":\"true\",\"dragOnTop\":\"false\"},\"className\":\"Circle\"},{\"attrs\":{\"x\":971,\"y\":315,\"stroke\":\"#666\",\"fill\":\"#ddd\",\"radius\":\"8\",\"name\":\"bottomRight\",\"draggable\":\"true\",\"dragOnTop\":\"false\"},\"className\":\"Circle\"},{\"attrs\":{},\"className\":\"Group\",\"children\":[{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":711.5,\"y\":90,\"height\":225,\"width\":175,\"defaultStroke\":\"#ffff64\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":40,\"y\":32.5,\"width\":175,\"text\":\"USB Ethernet Module\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":175,\"height\":225,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":175,\"height\":225,\"stroke\":\"#ffff64\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":35,\"y\":90},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":532.5,\"y\":90,\"height\":225,\"width\":175,\"defaultStroke\":\"#ffff64\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":40,\"y\":32.5,\"width\":175,\"text\":\"USB Ethernet Module\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":175,\"height\":225,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":175,\"height\":225,\"stroke\":\"#ffff64\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":35,\"y\":90},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":882.5,\"y\":172,\"height\":82,\"width\":95,\"defaultStroke\":\"#d4b9ff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":10,\"y\":20,\"width\":95,\"text\":\"microSD slot\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\",\"x\":6.5,\"y\":88.5,\"rotation\":270},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":95,\"height\":82,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":95,\"height\":82,\"stroke\":\"#d4b9ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":3.5,\"y\":4.5,\"height\":75,\"width\":86},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":181,\"y\":12,\"height\":60,\"width\":60,\"defaultStroke\":\"#909bef\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":5,\"y\":12.5,\"width\":60,\"text\":\"USB Hub 4 Port\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":60,\"height\":60,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":60,\"height\":60,\"stroke\":\"#909bef\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":20,\"y\":10},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":425,\"y\":275,\"height\":40,\"width\":60,\"defaultStroke\":\"#e5b758\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":7.5,\"y\":5,\"width\":60,\"text\":\"Micro-B Jack\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":60,\"height\":40,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":60,\"height\":40,\"stroke\":\"#e5b758\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":7.5,\"y\":14,\"height\":31,\"width\":46},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":272,\"y\":1.5,\"height\":133,\"width\":254,\"defaultStroke\":\"#90f5ff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":76,\"y\":32,\"width\":254,\"text\":\"COM Connector\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":254,\"height\":133,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":254,\"height\":133,\"stroke\":\"#90f5ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":2,\"y\":4},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":208,\"y\":145,\"height\":170,\"width\":120,\"defaultStroke\":\"#66ccff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":19,\"y\":55,\"width\":120,\"text\":\"Dual Stacked USB\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":120,\"height\":170,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":120,\"height\":170,\"stroke\":\"#66ccff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":10,\"y\":35},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":901.5,\"y\":12,\"height\":100,\"width\":65,\"defaultStroke\":\"#8bff8f\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":15,\"y\":25,\"width\":65,\"text\":\"5V/5A Regulator\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":65,\"height\":100,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":65,\"height\":100,\"stroke\":\"#8bff8f\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":12.5,\"y\":10},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":489.5,\"y\":279.5,\"height\":35,\"width\":35,\"defaultStroke\":\"#e5b758\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":4,\"y\":8,\"width\":35,\"text\":\"Tactile Switch\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":35,\"height\":35,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":35,\"height\":35,\"stroke\":\"#e5b758\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":5,\"y\":5},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":718.5,\"y\":5.5,\"height\":75,\"width\":75,\"defaultStroke\":\"#e5b758\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":15,\"y\":20,\"width\":75,\"text\":\"3.5V/1.5A Regulator\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":75,\"height\":75,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":75,\"height\":75,\"stroke\":\"#ca73ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{},\"className\":\"Group\",\"children\":[]}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":929,\"y\":284,\"height\":30,\"width\":30,\"defaultStroke\":\"#ca73ff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":6,\"y\":11,\"width\":30,\"text\":\"LED\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":30,\"height\":30,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":30,\"height\":30,\"stroke\":\"#ff00ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":3.75,\"y\":8,\"height\":14,\"width\":22.5},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":892,\"y\":284,\"height\":30,\"width\":30,\"defaultStroke\":\"#ff00ff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":6,\"y\":11,\"width\":30,\"text\":\"LED\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":30,\"height\":30,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":30,\"height\":30,\"stroke\":\"#ff00ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":3.75,\"y\":8,\"height\":14,\"width\":22.5},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":130,\"y\":285,\"height\":30,\"width\":30,\"defaultStroke\":\"#ff00ff\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":6,\"y\":11,\"width\":30,\"text\":\"LED\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":30,\"height\":30,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":30,\"height\":30,\"stroke\":\"#ff00ff\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":3.75,\"y\":8,\"height\":14,\"width\":22.5},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":330,\"y\":205,\"height\":110,\"width\":90,\"defaultStroke\":\"#debd37\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":10,\"y\":25,\"width\":90,\"text\":\"Barrel Connector (20V 3A)\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":90,\"height\":110,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":90,\"height\":110,\"stroke\":\"#debd37\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":10,\"y\":10},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":128.5,\"y\":97,\"height\":100,\"width\":65,\"defaultStroke\":\"#8bff8f\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":15,\"y\":25,\"width\":65,\"text\":\"5V/5A Regulator\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":65,\"height\":100,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":65,\"height\":100,\"stroke\":\"#8bff8f\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":12.5,\"y\":10},\"className\":\"Image\"}]}]},{\"attrs\":{\"draggable\":\"true\",\"name\":\"moduleGroup\",\"x\":167.5,\"y\":278.5,\"height\":35,\"width\":35,\"defaultStroke\":\"#e5b758\",\"isStrokeRed\":false},\"className\":\"Group\",\"children\":[{\"attrs\":{\"fill\":\"black\",\"x\":4,\"y\":8,\"width\":35,\"text\":\"Tactile Switch\",\"fontSize\":10,\"fontFamily\":\"sans-serif\"},\"className\":\"Text\"},{\"attrs\":{\"name\":\"innerGroup\"},\"className\":\"Group\",\"children\":[{\"attrs\":{\"width\":35,\"height\":35,\"fill\":\"green\",\"opacity\":0.1},\"className\":\"Rect\"},{\"attrs\":{\"name\":\"moduleBorder\",\"width\":35,\"height\":35,\"stroke\":\"#e5b758\",\"strokeWidth\":1},\"className\":\"Rect\"},{\"attrs\":{\"x\":5,\"y\":5},\"className\":\"Image\"}]}]}]}]}]}]}",
    "height": 315,
    "width": 864,
  }
}
