export const sampleProject = {
  isSampleProject: true,
  name: 'Example Project',
  __v: 0,
  modules: [
    {
      _id: '5bee9b576472530cf4f5d181',
      x: 229,
      y: 15.5,
      stroke: '#01579b',
      width: 254,
      height: 133,
      rotation: 360,
      boundToSideIndex: null,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'COM Connector',
      textX: 76,
      textY: 32,
      imageX: 2,
      imageY: 4,
      imageWidth: 250,
      imageHeight: 125,
      imageSrc: 'images/COM-connector.svg',
      iconSrc: 'images/COM-connector.svg',
      iconHeight: '70px',
      price: 48,
      id: '105',
      dependencies: [
        '109'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d180',
      x: 9.5,
      y: 181,
      stroke: '#7e57c2',
      width: 65,
      height: 100,
      rotation: 360,
      boundToSideIndex: null,
      innerGroupX: 0,
      innerGroupY: 0,
      text: '5V/5A Regulator',
      textX: 15,
      textY: 25,
      imageX: 12.5,
      imageY: 10,
      imageWidth: 40,
      imageHeight: 80,
      imageSrc: 'images/regulator-5V5A.svg',
      iconSrc: 'images/regulator-5V5A-icon.svg',
      iconHeight: '70px',
      price: 9.75,
      id: '109',
      dependencies: [
        '110'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d17f',
      x: 226,
      y: 243,
      stroke: '#00796b',
      width: 90,
      height: 110,
      rotation: 360,
      boundToSideIndex: 0,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'Barrel Connector (20V 3A)',
      textX: 10,
      textY: 25,
      imageX: 10,
      imageY: 10,
      imageWidth: 70,
      imageHeight: 100,
      imageSrc: 'images/barrel-connector.svg',
      iconSrc: 'images/barrel-connector-icon.svg',
      iconHeight: '70px',
      price: 5,
      id: '110',
      dependencies: []
    },
    {
      _id: '5bee9b576472530cf4f5d17e',
      x: 323,
      y: 253,
      stroke: '#0288d1',
      width: 120,
      height: 100,
      rotation: 180,
      boundToSideIndex: 0,
      innerGroupX: 120,
      innerGroupY: 100,
      text: 'HDMI Connector',
      textX: 22.5,
      textY: 35,
      imageX: 15,
      imageY: -2,
      imageWidth: 90,
      imageHeight: 70,
      imageSrc: 'images/hdmi-connector.svg',
      iconSrc: 'images/hdmi-connector-icon.svg',
      iconHeight: '70px',
      price: 3.25,
      id: '112',
      dependencies: [
        '105'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d17d',
      x: 857.5,
      y: 27,
      stroke: '#7e57c2',
      width: 65,
      height: 100,
      rotation: 180,
      boundToSideIndex: null,
      innerGroupX: 65,
      innerGroupY: 100,
      text: '5V/5A Regulator',
      textX: 15,
      textY: 25,
      imageX: 12.5,
      imageY: 10,
      imageWidth: 40,
      imageHeight: 80,
      imageSrc: 'images/regulator-5V5A.svg',
      iconSrc: 'images/regulator-5V5A-icon.svg',
      iconHeight: '70px',
      price: 9.75,
      id: '109',
      dependencies: [
        '110'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d17c',
      x: 670.5,
      y: 128,
      stroke: '#009688',
      width: 175,
      height: 225,
      rotation: 0,
      boundToSideIndex: 0,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'USB Ethernet Module',
      textX: 40,
      textY: 32.5,
      imageX: 35,
      imageY: 90,
      imageWidth: 105,
      imageHeight: 145,
      imageSrc: 'images/usb-ethernet-module-2.svg',
      iconSrc: 'images/usb-ethernet-module-icon.svg',
      iconHeight: '70px',
      price: 12,
      id: '102',
      dependencies: [
        '103',
        '105',
        '111'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d17b',
      x: 381,
      y: 171,
      stroke: '#00796b',
      width: 60,
      height: 60,
      rotation: 0,
      boundToSideIndex: null,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'USB Hub 4 Port',
      textX: 5,
      textY: 12.5,
      imageX: 20,
      imageY: 10,
      imageWidth: 30,
      imageHeight: 30,
      imageSrc: 'images/USB-hub-4-port.svg',
      iconSrc: 'images/USB-hub-4-port-icon.svg',
      iconHeight: '70px',
      price: 2.25,
      id: '103',
      dependencies: [
        '105',
        '111'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d17a',
      x: 582.5,
      y: 14.5,
      stroke: '#37474f',
      width: 75,
      height: 75,
      rotation: 180,
      boundToSideIndex: null,
      text: '3.5V/1.5A Regulator',
      textX: 15,
      textY: 20,
      innerGroupX: 75,
      innerGroupY: 75,
      imageX: null,
      imageY: null,
      imageWidth: null,
      imageHeight: null,
      imageSrc: 'images/transparent-dummy-image.svg',
      iconSrc: 'images/regulator-icon.svg',
      iconHeight: '70px',
      price: 4.25,
      id: '111',
      dependencies: [
        '110'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d179',
      x: 489.5,
      y: 128,
      stroke: '#009688',
      width: 175,
      height: 225,
      rotation: 0,
      boundToSideIndex: 0,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'USB Ethernet Module',
      textX: 40,
      textY: 32.5,
      imageX: 35,
      imageY: 90,
      imageWidth: 105,
      imageHeight: 145,
      imageSrc: 'images/usb-ethernet-module-2.svg',
      iconSrc: 'images/usb-ethernet-module-icon.svg',
      iconHeight: '70px',
      price: 12,
      id: '102',
      dependencies: [
        '103',
        '105',
        '111'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d178',
      x: 794.5,
      y: 204,
      stroke: '#7e57c2',
      width: 95,
      height: 82,
      rotation: 270,
      boundToSideIndex: 3,
      innerGroupX: 6.5,
      innerGroupY: 88.5,
      text: 'MicroSD Slot',
      textX: 10,
      textY: 20,
      imageX: 3.5,
      imageY: 4.5,
      imageWidth: 86,
      imageHeight: 75,
      imageSrc: 'images/microsd-slot.svg',
      iconSrc: 'images/microsd-slot-icon.svg',
      iconHeight: '70px',
      price: 5,
      id: '101',
      dependencies: [
        '105'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d177',
      x: 447.5,
      y: 317.5,
      stroke: '#01579b',
      width: 35,
      height: 35,
      rotation: 0,
      boundToSideIndex: null,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'Tactile Switch',
      textX: 4,
      textY: 8,
      imageX: 5,
      imageY: 5,
      imageWidth: 25,
      imageHeight: 25,
      imageSrc: 'images/tactile-switch.svg',
      iconSrc: 'images/tactile-switch-icon.svg',
      iconHeight: '70px',
      price: 1.2,
      id: '107',
      dependencies: [
        '105'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d176',
      x: 102,
      y: 183,
      stroke: '#009688',
      width: 120,
      height: 170,
      rotation: 0,
      boundToSideIndex: 0,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'USB Type-A Jack',
      textX: 19,
      textY: 55,
      imageX: 10,
      imageY: 35,
      imageWidth: 100,
      imageHeight: 135,
      imageSrc: 'images/dual-stacked-usb.svg',
      iconSrc: 'images/dual-stacked-usb-icon.svg',
      iconHeight: '70px',
      price: 13.5,
      id: '106',
      dependencies: [
        '109'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d175',
      x: 61.5,
      y: 314.5,
      stroke: '#01579b',
      width: 35,
      height: 35,
      rotation: 90,
      boundToSideIndex: null,
      innerGroupX: 35,
      innerGroupY: 0,
      text: 'Tactile Switch',
      textX: 4,
      textY: 8,
      imageX: 5,
      imageY: 5,
      imageWidth: 25,
      imageHeight: 25,
      imageSrc: 'images/tactile-switch.svg',
      iconSrc: 'images/tactile-switch-icon.svg',
      iconHeight: '70px',
      price: 1.2,
      id: '107',
      dependencies: [
        '105'
      ]
    },
    {
      _id: '5bee9b576472530cf4f5d174',
      x: 80,
      y: 46,
      stroke: '#00796b',
      width: 60,
      height: 60,
      rotation: 0,
      boundToSideIndex: null,
      innerGroupX: 0,
      innerGroupY: 0,
      text: 'USB Hub 4 Port',
      textX: 5,
      textY: 12.5,
      imageX: 20,
      imageY: 10,
      imageWidth: 30,
      imageHeight: 30,
      imageSrc: 'images/USB-hub-4-port.svg',
      iconSrc: 'images/USB-hub-4-port-icon.svg',
      iconHeight: '70px',
      price: 2.25,
      id: '103',
      dependencies: [
        '105',
        '111'
      ]
    }
  ],
  boardSpecs: {
    y: 274,
    x: 340,
    thumbnail: '{"attrs":{"width":956,"height":373},"className":"Stage","children":[{"attrs":{"name":"boardLayer"},"className":"Layer","children":[{"attrs":{"name":"boardGroup","x":10,"y":10,"width":936,"height":353,"draggable":"true"},"className":"Group","children":[{"attrs":{"name":"board","width":936,"height":353,"fill":"#e3e3e5","opacity":"0.5","isStrokeRed":false},"className":"Rect"},{"attrs":{"stroke":"#666","fill":"#ddd","radius":"8","name":"topLeft","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"x":936,"stroke":"#666","fill":"#ddd","radius":"8","name":"topRight","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"y":353,"stroke":"#666","fill":"#ddd","radius":"8","name":"bottomLeft","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"x":936,"y":353,"stroke":"#666","fill":"#ddd","radius":"8","name":"bottomRight","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"name":"moduleGroup"},"className":"Group","children":[{"attrs":{"draggable":"true","name":"moduleGroup","x":229,"y":15.5,"height":133,"width":254,"defaultStroke":"#01579b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":76,"y":32,"width":254,"text":"COM Connector","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","rotation":360},"className":"Group","children":[{"attrs":{"width":254,"height":133,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":254,"height":133,"stroke":"#01579b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":2,"y":4,"src":"images/COM-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":9.5,"y":181,"height":100,"width":65,"defaultStroke":"#7e57c2","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":15,"y":25,"width":65,"text":"5V/5A Regulator","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","rotation":360},"className":"Group","children":[{"attrs":{"width":65,"height":100,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":65,"height":100,"stroke":"#7e57c2","strokeWidth":1.5},"className":"Rect"},{"attrs":{"x":12.5,"y":10,"src":"images/regulator-5V5A.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":226,"y":243,"height":110,"width":90,"defaultStroke":"#00796b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":10,"y":25,"width":90,"text":"Barrel Connector (20V 3A)","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","rotation":360},"className":"Group","children":[{"attrs":{"width":90,"height":110,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":90,"height":110,"stroke":"#00796b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":10,"y":10,"src":"images/barrel-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":323,"y":253,"height":100,"width":120,"defaultStroke":"#0288d1","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":22.5,"y":35,"width":120,"text":"HDMI Connector","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":120,"y":100,"rotation":180},"className":"Group","children":[{"attrs":{"width":120,"height":100,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":120,"height":100,"stroke":"#0288d1","strokeWidth":1},"className":"Rect"},{"attrs":{"x":15,"y":-2,"src":"images/hdmi-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":857.5,"y":27,"height":100,"width":65,"defaultStroke":"#7e57c2","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":15,"y":25,"width":65,"text":"5V/5A Regulator","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":65,"y":100,"rotation":180},"className":"Group","children":[{"attrs":{"width":65,"height":100,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":65,"height":100,"stroke":"#7e57c2","strokeWidth":1},"className":"Rect"},{"attrs":{"x":12.5,"y":10,"src":"images/regulator-5V5A.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":670.5,"y":128,"height":225,"width":175,"defaultStroke":"#009688","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":40,"y":32.5,"width":175,"text":"USB Ethernet Module","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":175,"height":225,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":175,"height":225,"stroke":"#009688","strokeWidth":1},"className":"Rect"},{"attrs":{"x":35,"y":90,"src":"images/usb-ethernet-module-2.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":381,"y":171,"height":60,"width":60,"defaultStroke":"#00796b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":5,"y":12.5,"width":60,"text":"USB Hub 4 Port","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":60,"height":60,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":60,"height":60,"stroke":"#00796b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":20,"y":10,"src":"images/USB-hub-4-port.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":582.5,"y":14.5,"height":75,"width":75,"defaultStroke":"#37474f","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":15,"y":20,"width":75,"text":"3.5V/1.5A Regulator","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","rotation":180,"x":75,"y":75},"className":"Group","children":[{"attrs":{"width":75,"height":75,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":75,"height":75,"stroke":"#37474f","strokeWidth":1},"className":"Rect"},{"attrs":{"src":"images/transparent-dummy-image.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":489.5,"y":128,"height":225,"width":175,"defaultStroke":"#009688","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":40,"y":32.5,"width":175,"text":"USB Ethernet Module","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":175,"height":225,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":175,"height":225,"stroke":"#009688","strokeWidth":1},"className":"Rect"},{"attrs":{"x":35,"y":90,"src":"images/usb-ethernet-module-2.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":847.5,"y":204,"height":82,"width":95,"defaultStroke":"#7e57c2","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":10,"y":20,"width":95,"text":"MicroSD Slot","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":6.5,"y":88.5,"rotation":270},"className":"Group","children":[{"attrs":{"width":95,"height":82,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":95,"height":82,"stroke":"#7e57c2","strokeWidth":1},"className":"Rect"},{"attrs":{"x":3.5,"y":4.5,"height":75,"width":86,"src":"images/microsd-slot.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":447.5,"y":317.5,"height":35,"width":35,"defaultStroke":"#01579b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":4,"y":8,"width":35,"text":"Tactile Switch","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":35,"height":35,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":35,"height":35,"stroke":"#01579b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":5,"y":5,"src":"images/tactile-switch.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":102,"y":183,"height":170,"width":120,"defaultStroke":"#009688","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":19,"y":55,"width":120,"text":"USB Type-A Jack","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":120,"height":170,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":120,"height":170,"stroke":"#009688","strokeWidth":1},"className":"Rect"},{"attrs":{"x":10,"y":35,"src":"images/dual-stacked-usb.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":61.5,"y":314.5,"height":35,"width":35,"defaultStroke":"#01579b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":4,"y":8,"width":35,"text":"Tactile Switch","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":35,"rotation":90},"className":"Group","children":[{"attrs":{"width":35,"height":35,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":35,"height":35,"stroke":"#01579b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":5,"y":5,"src":"images/tactile-switch.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":80,"y":46,"height":60,"width":60,"defaultStroke":"#00796b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":5,"y":12.5,"width":60,"text":"USB Hub 4 Port","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":60,"height":60,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":60,"height":60,"stroke":"#00796b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":20,"y":10,"src":"images/USB-hub-4-port.svg","name":"image"},"className":"Image"}]}]}]}]}]}]}',
    height: 353,
    width: 936
  }
}
