export const sampleProject = {
    name: 'Example Project',
    isSampleProject: true,
    modules: [
      {
        x: 124.5,
        y: 110.5,
        stroke: '#01579b',
        width: 254,
        height: 133,
        rotation: 90,
        boundToSideIndex: null,
        innerGroupX: 193.5,
        innerGroupY: -60.5,
        text: 'COM Connector',
        textX: 76,
        textY: 32,
        imageX: 2,
        imageY: 4,
        imageWidth: 250,
        imageHeight: 125,
        imageSrc: 'images/COM-connector.svg',
        iconSrc: 'images/COM-connector.svg',
        iconHeight: '70px',
        price: 48,
        id: '105',
        dependencies: [
          '109'
        ]
      },
      {
        x: 23,
        y: 93,
        stroke: '#7e57c2',
        width: 65,
        height: 100,
        rotation: 90,
        boundToSideIndex: null,
        innerGroupX: 82.5,
        innerGroupY: 17.5,
        text: '5V/5A Regulator',
        textX: 15,
        textY: 25,
        imageX: 12.5,
        imageY: 10,
        imageWidth: 40,
        imageHeight: 80,
        imageSrc: 'images/regulator-5V5A.svg',
        iconSrc: 'images/regulator-5V5A-icon.svg',
        iconHeight: '70px',
        price: 9.75,
        id: '109',
        dependencies: [
          '110'
        ]
      },
      {
        x: 9,
        y: 0,
        stroke: '#00796b',
        width: 90,
        height: 110,
        rotation: 90,
        boundToSideIndex: 1,
        innerGroupX: 100,
        innerGroupY: 10,
        text: 'Barrel Connector (20V 3A)',
        textX: 10,
        textY: 25,
        imageX: 10,
        imageY: 10,
        imageWidth: 70,
        imageHeight: 100,
        imageSrc: 'images/barrel-connector.svg',
        iconSrc: 'images/barrel-connector-icon.svg',
        iconHeight: '70px',
        price: 5,
        id: '110',
        dependencies: []
      },
      {
        x: 24,
        y: 156,
        stroke: '#009688',
        width: 120,
        height: 170,
        rotation: 90,
        boundToSideIndex: 1,
        innerGroupX: 145,
        innerGroupY: 25,
        text: 'USB Type-A Jack',
        textX: 19,
        textY: 55,
        imageX: 10,
        imageY: 35,
        imageWidth: 100,
        imageHeight: 135,
        imageSrc: 'images/dual-stacked-usb.svg',
        iconSrc: 'images/dual-stacked-usb-icon.svg',
        iconHeight: '70px',
        price: 13.5,
        id: '106',
        dependencies: [
          '109'
        ]
      },
      {
        x: 438.5,
        y: 207,
        stroke: '#7e57c2',
        width: 95,
        height: 82,
        rotation: 270,
        boundToSideIndex: 3,
        innerGroupX: 6.5,
        innerGroupY: 88.5,
        text: 'MicroSD Slot',
        textX: 10,
        textY: 20,
        imageX: 3.5,
        imageY: 4.5,
        imageWidth: 86,
        imageHeight: 75,
        imageSrc: 'images/microsd-slot.svg',
        iconSrc: 'images/microsd-slot-icon.svg',
        iconHeight: '70px',
        price: 5,
        id: '101',
        dependencies: [
          '105'
        ]
      },
      {
        id: '112',
        price: 3.25,
        iconHeight: '70px',
        iconSrc: 'images/hdmi-connector-icon.svg',
        imageSrc: 'images/hdmi-connector.svg',
        imageHeight: 70,
        imageWidth: 90,
        imageY: -2,
        imageX: 15,
        textY: 35,
        textX: 22.5,
        text: 'HDMI Connector',
        innerGroupY: -10,
        innerGroupX: 110,
        boundToSideIndex: 3,
        rotation: 90,
        height: 100,
        width: 120,
        stroke: '#0288d1',
        y: 64,
        x: 417,
        dependencies: [
          '105'
        ]
      },
      {
        id: '108',
        price: 9.75,
        iconHeight: '70px',
        iconSrc: 'images/LED-icon.svg',
        imageSrc: 'images/LED.svg',
        imageHeight: 14,
        imageWidth: 22.5,
        imageY: 8,
        imageX: 3.75,
        textY: 11,
        textX: 6,
        text: 'LED',
        innerGroupY: 0,
        innerGroupX: 0,
        boundToSideIndex: null,
        rotation: 0,
        height: 30,
        width: 30,
        stroke: '#0288d1',
        y: 12,
        x: 342.5,
        dependencies: [
          '105'
        ]
      },
      {
        id: '107',
        price: 1.2,
        iconHeight: '70px',
        iconSrc: 'images/tactile-switch-icon.svg',
        imageSrc: 'images/tactile-switch.svg',
        imageHeight: 25,
        imageWidth: 25,
        imageY: 5,
        imageX: 5,
        textY: 8,
        textX: 4,
        text: 'Tactile Switch',
        innerGroupY: 0,
        innerGroupX: 0,
        boundToSideIndex: null,
        rotation: 0,
        height: 35,
        width: 35,
        stroke: '#01579b',
        y: 9.5,
        x: 394,
        dependencies: [
          '105'
        ]
      }
    ],
    boardSpecs: {
      y: 285,
      x: 341.5,
      thumbnail: '{"attrs":{"width":468,"height":335},"className":"Stage","children":[{"attrs":{"name":"boardLayer"},"className":"Layer","children":[{"attrs":{"name":"boardGroup","x":9,"y":-33,"width":448,"height":315,"draggable":"true"},"className":"Group","children":[{"attrs":{"name":"board","x":1,"y":43,"width":448,"height":315,"fill":"#e3e3e5","opacity":"0.5","isStrokeRed":false},"className":"Rect"},{"attrs":{"x":1,"y":43,"stroke":"#666","fill":"#ddd","radius":"8","name":"topLeft","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"x":449,"y":43,"stroke":"#666","fill":"#ddd","radius":"8","name":"topRight","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"x":1,"y":358,"stroke":"#666","fill":"#ddd","radius":"8","name":"bottomLeft","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"x":449,"y":358,"stroke":"#666","fill":"#ddd","radius":"8","name":"bottomRight","draggable":"true","dragOnTop":"false"},"className":"Circle"},{"attrs":{"name":"moduleGroup"},"className":"Group","children":[{"attrs":{"draggable":"true","name":"moduleGroup","x":125.5,"y":153.5,"height":133,"width":254,"defaultStroke":"#01579b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":76,"y":32,"width":254,"text":"COM Connector","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":193.5,"y":-60.5,"rotation":90},"className":"Group","children":[{"attrs":{"width":254,"height":133,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":254,"height":133,"stroke":"#01579b","strokeWidth":1.5},"className":"Rect"},{"attrs":{"x":2,"y":4,"src":"images/COM-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":24,"y":136,"height":100,"width":65,"defaultStroke":"#7e57c2","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":15,"y":25,"width":65,"text":"5V/5A Regulator","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":82.5,"y":17.5,"rotation":90},"className":"Group","children":[{"attrs":{"width":65,"height":100,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":65,"height":100,"stroke":"#7e57c2","strokeWidth":1},"className":"Rect"},{"attrs":{"x":12.5,"y":10,"src":"images/regulator-5V5A.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":11,"y":43,"height":110,"width":90,"defaultStroke":"#00796b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":10,"y":25,"width":90,"text":"Barrel Connector (20V 3A)","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":100,"y":10,"rotation":90},"className":"Group","children":[{"attrs":{"width":90,"height":110,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":90,"height":110,"stroke":"#00796b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":10,"y":10,"src":"images/barrel-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":26,"y":199,"height":170,"width":120,"defaultStroke":"#009688","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":19,"y":55,"width":120,"text":"USB Type-A Jack","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":145,"y":25,"rotation":90},"className":"Group","children":[{"attrs":{"width":120,"height":170,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":120,"height":170,"stroke":"#009688","strokeWidth":1},"className":"Rect"},{"attrs":{"x":10,"y":35,"src":"images/dual-stacked-usb.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":360.5,"y":250,"height":82,"width":95,"defaultStroke":"#7e57c2","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":10,"y":20,"width":95,"text":"MicroSD Slot","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":6.5,"y":88.5,"rotation":270},"className":"Group","children":[{"attrs":{"width":95,"height":82,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":95,"height":82,"stroke":"#7e57c2","strokeWidth":1},"className":"Rect"},{"attrs":{"x":3.5,"y":4.5,"height":75,"width":86,"src":"images/microsd-slot.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":339,"y":107,"height":100,"width":120,"defaultStroke":"#0288d1","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":22.5,"y":35,"width":120,"text":"HDMI Connector","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup","x":110,"y":-10,"rotation":90},"className":"Group","children":[{"attrs":{"width":120,"height":100,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":120,"height":100,"stroke":"#0288d1","strokeWidth":1},"className":"Rect"},{"attrs":{"x":15,"y":-2,"src":"images/hdmi-connector.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":343.5,"y":55,"height":30,"width":30,"defaultStroke":"#0288d1","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":6,"y":11,"width":30,"text":"LED","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":30,"height":30,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":30,"height":30,"stroke":"#0288d1","strokeWidth":1},"className":"Rect"},{"attrs":{"x":3.75,"y":8,"height":14,"width":22.5,"src":"images/LED.svg","name":"image"},"className":"Image"}]}]},{"attrs":{"draggable":"true","name":"moduleGroup","x":395,"y":52.5,"height":35,"width":35,"defaultStroke":"#01579b","isStrokeRed":false},"className":"Group","children":[{"attrs":{"fill":"black","x":4,"y":8,"width":35,"text":"Tactile Switch","fontSize":10,"fontFamily":"sans-serif"},"className":"Text"},{"attrs":{"name":"innerGroup"},"className":"Group","children":[{"attrs":{"width":35,"height":35,"fill":"green","opacity":0.1},"className":"Rect"},{"attrs":{"name":"moduleBorder","width":35,"height":35,"stroke":"#01579b","strokeWidth":1},"className":"Rect"},{"attrs":{"x":5,"y":5,"src":"images/tactile-switch.svg","name":"image"},"className":"Image"}]}]}]}]}]}]}',
      height: 315,
      width: 448
    }
  }
