export const toolTips = [
  {
    text: 'Drag the COM Connector module onto the board ',
    type: 'click',
    selector: /* '.save-button', */'.toolTip-105',
    position: 'right',
    trigger: /* '.save-button',*/ '.com-connector-tooltip',
    style: {
      backgroundColor: 'white',
      borderRadius: 0,
      color: 'black',
      mainColor: '#ff67b4',
      textAlign: 'center',
      width: '29rem',
    },
  },
  {
    text: 'Drag 5V/5A Regulator to the board',
    type: 'click',
    selector: /* '.save-button', */'.toolTip-109',
    position: 'right',
    trigger: /* '.save-button',*/ '.regulator-tooltip',
    style: {
      backgroundColor: 'white',
      borderRadius: 0,
      color: 'black',
      mainColor: '#ff67b4',
      textAlign: 'center',
      width: '29rem',
    },
  },
  {
    text: 'Add the DC Barrel Connector the board',
    type: 'click',
    selector: /* '.save-button', */'.toolTip-110',
    position: 'right',
    trigger: /* '.save-button',*/ '.barrel-connector-tooltip',
    style: {
      backgroundColor: 'white',
      borderRadius: 0,
      color: 'black',
      mainColor: '#ff67b4',
      textAlign: 'center',
      width: '29rem',
    },
  },
];
