const demoProject = {
  "name": "Dual Ethernet Board",
  "ownerId": "5a94fddfe718bc62f2608486",
  "modules": [
    {
      "id": "105",
      "price": 48,
      "iconHeight": "70px",
      "iconSrc": "images/COM-connector.svg",
      "imageSrc": "images/COM-connector.svg",
      "imageHeight": 125,
      "imageWidth": 250,
      "imageY": 4,
      "imageX": 2,
      "textY": 32,
      "textX": 76,
      "text": "COM Connector",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 133,
      "width": 254,
      "stroke": "#01579b",
      "y": 12,
      "x": 197,
      "dependencies": [
        "109"
      ]
    },
    {
      "id": "109",
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-5V5A-icon.svg",
      "imageSrc": "images/regulator-5V5A.svg",
      "imageHeight": 80,
      "imageWidth": 40,
      "imageY": 10,
      "imageX": 12.5,
      "textY": 25,
      "textX": 15,
      "text": "5V/5A Regulator",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 100,
      "width": 65,
      "stroke": "#7e57c2",
      "y": 33.5,
      "x": 66.5,
      "dependencies": [
        "110"
      ]
    },
    {
      "id": "110",
      "price": 5,
      "iconHeight": "70px",
      "iconSrc": "images/barrel-connector-icon.svg",
      "imageSrc": "images/barrel-connector.svg",
      "imageHeight": 100,
      "imageWidth": 70,
      "imageY": 10,
      "imageX": 10,
      "textY": 25,
      "textX": 10,
      "text": "Barrel Connector (20V 3A)",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 110,
      "width": 90,
      "stroke": "#00796b",
      "y": 218,
      "x": 253,
      "dependencies": []
    },
    {
      "id": "107",
      "price": 1.2,
      "iconHeight": "70px",
      "iconSrc": "images/tactile-switch-icon.svg",
      "imageSrc": "images/tactile-switch.svg",
      "imageHeight": 25,
      "imageWidth": 25,
      "imageY": 5,
      "imageX": 5,
      "textY": 8,
      "textX": 4,
      "text": "Tactile Switch",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 35,
      "width": 35,
      "stroke": "#01579b",
      "y": 256,
      "x": 72.5,
      "dependencies": [
        "105"
      ]
    },
    {
      "id": "108",
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#0288d1",
      "y": 258.5,
      "x": 21,
      "dependencies": [
        "105"
      ]
    },
    {
      "id": "106",
      "price": 13.5,
      "iconHeight": "70px",
      "iconSrc": "images/dual-stacked-usb-icon.svg",
      "imageSrc": "images/dual-stacked-usb.svg",
      "imageHeight": 135,
      "imageWidth": 100,
      "imageY": 35,
      "imageX": 10,
      "textY": 55,
      "textX": 19,
      "text": "USB Type-A Jack",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 170,
      "width": 120,
      "stroke": "#009688",
      "y": 158,
      "x": 122,
      "dependencies": [
        "109"
      ]
    },
    {
      "id": "104",
      "price": 2.25,
      "iconHeight": "70px",
      "iconSrc": "images/micro-b-jack-icon.svg",
      "imageSrc": "images/micro-b-jack.svg",
      "imageHeight": 31,
      "imageWidth": 46,
      "imageY": 14,
      "imageX": 7.5,
      "textY": 5,
      "textX": 7.5,
      "text": "Micro-B Jack",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 40,
      "width": 60,
      "stroke": "#0277bd",
      "y": 288,
      "x": 351,
      "dependencies": [
        "105"
      ]
    },
    {
      "id": "102",
      "price": 12,
      "iconHeight": "70px",
      "iconSrc": "images/usb-ethernet-module-icon.svg",
      "imageSrc": "images/usb-ethernet-module-2.svg",
      "imageHeight": 145,
      "imageWidth": 105,
      "imageY": 90,
      "imageX": 35,
      "textY": 32.5,
      "textX": 40,
      "text": "USB Ethernet Module",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 225,
      "width": 175,
      "stroke": "#009688",
      "y": 130,
      "x": 461.5,
      "dependencies": [
        "103",
        "105",
        "111"
      ]
    },
    {
      "id": "103",
      "price": 2.25,
      "iconHeight": "70px",
      "iconSrc": "images/USB-hub-4-port-icon.svg",
      "imageSrc": "images/USB-hub-4-port.svg",
      "imageHeight": 30,
      "imageWidth": 30,
      "imageY": 10,
      "imageX": 20,
      "textY": 12.5,
      "textX": 5,
      "text": "USB Hub 4 Port",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 60,
      "width": 60,
      "stroke": "#00796b",
      "y": 165.5,
      "x": 306,
      "dependencies": [
        "105",
        "111"
      ]
    },
    {
      "id": "111",
      "price": 4.25,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-icon.svg",
      "imageSrc": "images/transparent-dummy-image.svg",
      "imageHeight": null,
      "imageWidth": null,
      "imageY": null,
      "imageX": null,
      "innerGroupY": null,
      "innerGroupX": null,
      "textY": 20,
      "textX": 15,
      "text": "3.5V/1.5A Regulator",
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 75,
      "width": 75,
      "stroke": "#37474f",
      "y": 16,
      "x": 704.5,
      "dependencies": [
        "110"
      ]
    },
    {
      "id": "102",
      "price": 12,
      "iconHeight": "70px",
      "iconSrc": "images/usb-ethernet-module-icon.svg",
      "imageSrc": "images/usb-ethernet-module-2.svg",
      "imageHeight": 145,
      "imageWidth": 105,
      "imageY": 90,
      "imageX": 35,
      "textY": 32.5,
      "textX": 40,
      "text": "USB Ethernet Module",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": 0,
      "rotation": 0,
      "height": 225,
      "width": 175,
      "stroke": "#009688",
      "y": 133,
      "x": 637.5,
      "dependencies": [
        "103",
        "105",
        "111"
      ]
    },
    {
      "id": "101",
      "price": 5,
      "iconHeight": "70px",
      "iconSrc": "images/microsd-slot-icon.svg",
      "imageSrc": "images/microsd-slot.svg",
      "imageHeight": 75,
      "imageWidth": 86,
      "imageY": 4.5,
      "imageX": 3.5,
      "textY": 20,
      "textX": 10,
      "text": "MicroSD Slot",
      "innerGroupY": 88.5,
      "innerGroupX": 6.5,
      "boundToSideIndex": 3,
      "rotation": 270,
      "height": 82,
      "width": 95,
      "stroke": "#7e57c2",
      "y": 188,
      "x": 854.5,
      "dependencies": [
        "105"
      ]
    },
    {
      "id": "109",
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/regulator-5V5A-icon.svg",
      "imageSrc": "images/regulator-5V5A.svg",
      "imageHeight": 80,
      "imageWidth": 40,
      "imageY": 10,
      "imageX": 12.5,
      "textY": 25,
      "textX": 15,
      "text": "5V/5A Regulator",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 100,
      "width": 65,
      "stroke": "#7e57c2",
      "y": 10.5,
      "x": 832.5,
      "dependencies": [
        "110"
      ]
    },
    {
      "id": "108",
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#0288d1",
      "y": 312.5,
      "x": 820,
      "dependencies": [
        "105"
      ]
    },
    {
      "id": "108",
      "price": 9.75,
      "iconHeight": "70px",
      "iconSrc": "images/LED-icon.svg",
      "imageSrc": "images/LED.svg",
      "imageHeight": 14,
      "imageWidth": 22.5,
      "imageY": 8,
      "imageX": 3.75,
      "textY": 11,
      "textX": 6,
      "text": "LED",
      "innerGroupY": 0,
      "innerGroupX": 0,
      "boundToSideIndex": null,
      "rotation": 0,
      "height": 30,
      "width": 30,
      "stroke": "#0288d1",
      "y": 312.5,
      "x": 860,
      "dependencies": [
        "105"
      ]
    }
  ],
  "board": {
    "y": 234.5,
    "x": 266,
    "height": 392,
    "width": 902
  },
  "__v": 0
}
module.exports = demoProject;
